#!/bin/bash
# 컴퓨터공학전공 2017E7441 김이삭
# 확장자에 따른 선택적 응용 프로그램을 실행하는 쉘 스크립트
# 	$# : number of arguments (인자의 수)
#	$0 : 프로그램명
#	$1~$9 : n번째 인자 
#	! : not 
# .c .mp3 .mp4 .odt .ods .pdf .png .jpg .txt

if [ $# -eq 0 ]; then
	echo "Usage : $0 file"
elif [ $# -ne 1 ]; then
	echo "Usage : $0, Only one factor is needed"
elif [ $# -eq 1 ]; then		# 인자가 하나인 경우
	if [ ! -e $1 ]; then	# 파일이 존재하지 않으면,
		echo "The file does not exist."
	else	# 파일이 존재하면,
		if [ -d $1 ]; then	# 만약 디렉토리이면
			echo "The argument of $0 must be a file"
			exit 1
		else 	# file이면 
			echo "argumnet[ $1 ]"
			arg=`basename $1`
			fileName="${arg%.*}"
			fileExtension="${arg##*.}"
		fi
		# echo $arg \| $fileName \| $fileExtension
		# 확장자 검사, 확장자에 따른 프로그램 실행
		# case
		case $fileExtension in
			c) vi $1
				;;
			txt) gedit $1 &
				;;
			mp3) rhythmbox $1 & 1>$2	
				;;
			mp4) vlc $1 & 1>&2
				;;
			pdf) evince -f $1 & 1>&2
				;;
			png) eog $1 &
				;;
			jpg) eog $1 &
				;;
			odt) libreoffice $1 &
				;;
			ods) libreoffice $1 &
				;;	
			java) gedit $1 &
				;;
			*) echo "Usage: $(basename $0) *.c|*.mp3|*.mp4|*.odt|*.ods|*.pdf|*.png|*.jpg|*.txt"
				exit 1
		esac

	fi 
fi
exit 0
